name: PublishToNPM

on:
  release:
    types: [published]

jobs:
  build-linux:
    name: Publish
    runs-on: ubuntu-latest

    steps:
    - name: Check out code onto host
      uses: actions/checkout@v2

    - name: Publish if version has been updated
      uses: pascalgn/npm-publish-action@1.3.8
      with:
        create_tag: true
        publish_command: "npm run build-library"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
