name: Unit tests

on:
  push:
    branches:
    - master

jobs:
  build-linux:
    name: Test plugin
    runs-on: ubuntu-latest

    steps:
    - name: Check out code onto host
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install node modules
      run: npm ci

    - name: Run unit tests
      run:  npm run test:unit
